# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from coconut.protos.tasks import task_pb2 as coconut_dot_protos_dot_tasks_dot_task__pb2


class RunnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Call = channel.unary_unary(
        '/Runner/Call',
        request_serializer=coconut_dot_protos_dot_tasks_dot_task__pb2.Signature.SerializeToString,
        response_deserializer=coconut_dot_protos_dot_tasks_dot_task__pb2.Reply.FromString,
        )


class RunnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Call(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RunnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Call': grpc.unary_unary_rpc_method_handler(
          servicer.Call,
          request_deserializer=coconut_dot_protos_dot_tasks_dot_task__pb2.Signature.FromString,
          response_serializer=coconut_dot_protos_dot_tasks_dot_task__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Runner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
