# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coconut/protos/runner/runner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from coconut.protos.tasks import task_pb2 as coconut_dot_protos_dot_tasks_dot_task__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coconut/protos/runner/runner.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z,gitlab.wisburg.com/coconut/coconut/pb/runner'),
  serialized_pb=_b('\n\"coconut/protos/runner/runner.proto\x1a\x1f\x63oconut/protos/tasks/task.proto22\n\x06Runner\x12(\n\x04\x43\x61ll\x12\x10.tasks.Signature\x1a\x0c.tasks.Reply\"\x00\x42.Z,gitlab.wisburg.com/coconut/coconut/pb/runnerb\x06proto3')
  ,
  dependencies=[coconut_dot_protos_dot_tasks_dot_task__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_RUNNER = _descriptor.ServiceDescriptor(
  name='Runner',
  full_name='Runner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=71,
  serialized_end=121,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='Runner.Call',
    index=0,
    containing_service=None,
    input_type=coconut_dot_protos_dot_tasks_dot_task__pb2._SIGNATURE,
    output_type=coconut_dot_protos_dot_tasks_dot_task__pb2._REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RUNNER)

DESCRIPTOR.services_by_name['Runner'] = _RUNNER

# @@protoc_insertion_point(module_scope)
